---
title: Folio Jekyll
timezone: UTC
collections:
  poetry:
    title: Poetry
    output: true
    permalink: "/poetry/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/portfolio/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@atelierscheidegger.ch
description: 'A simple, whitespace, helvetica based portfolio theme.

'
baseurl: 
url: 
twitter_username: ateliers_design
github_username: grafiche
markdown: kramdown
highlighter: rouge
paginate: 15
plugins_dir:
- jekyll-admin
paginate_path: "/blog/page:num/"
